#include "ft_malloc.h"

// testing allocs of all sizes

typedef struct s_nest {
  void *anything_else;
  void *something_else;
  char d;
  int a;
} t_nest;

typedef struct s_test {
  t_nest *nest;
  void *anything;
  void *something;
  char c;
  int b;
} t_test;

int main() {
  char *tiny1 = ft_malloc(sizeof(char) * 82);
  char *tiny2 = ft_malloc(sizeof(char) * 107);
  t_nest *tiny3 = ft_malloc(sizeof(t_nest));
  t_test *tiny4 = ft_malloc(sizeof(t_test));
  char *small1 = ft_malloc(sizeof(char) * 651);
  char *small2 = ft_malloc(sizeof(char) * 512);
  char *small3 = ft_malloc(sizeof(char) * 817);
  char *small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105); // issue
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);
  tiny1 = ft_malloc(sizeof(char) * 80);
  tiny2 = ft_malloc(sizeof(char) * 105);
  tiny3 = ft_malloc(sizeof(t_nest));
  tiny4 = ft_malloc(sizeof(t_test));
  small1 = ft_malloc(sizeof(char) * 651);
  small2 = ft_malloc(sizeof(char) * 512);
  small3 = ft_malloc(sizeof(char) * 817);
  small4 = ft_malloc(sizeof(char) * 353);
  free(tiny2);
  free(tiny3);
  free(small3);
  free(small1);

  show_alloc_mem();
  return 0;
}
