#include "../src/tester.cpp"
#include "ft_malloc.h"

// testing allocs of all sizes

typedef struct s_nest {
  void *anything_else;
  void *something_else;
  char d;
  int a;
} t_nest;

typedef struct s_test {
  t_nest *nest;
  void *anything;
  void *something;
  char c;
  int b;
} t_test;

int main() {
  Tester tester = Tester();
  char *tiny1 = (char *)tester.wrap_malloc(sizeof(char) * 82, 0);
  char *tiny2 = (char *)tester.wrap_malloc(sizeof(char) * 107, 0);
  t_nest *tiny3 = (t_nest *)tester.wrap_malloc(sizeof(t_nest), 0);
  t_test *tiny4 = (t_test *)tester.wrap_malloc(sizeof(t_test), 0);
  char *small1 = (char *)tester.wrap_malloc(sizeof(char) * 651, 0);
  char *small2 = (char *)tester.wrap_malloc(sizeof(char) * 512, 0);
  char *small3 = (char *)tester.wrap_malloc(sizeof(char) * 817, 0);
  char *small4 = (char *)tester.wrap_malloc(sizeof(char) * 353, 0);
  tester.wrap_free(tiny2);
  tester.wrap_free(tiny3);
  tester.wrap_free(small3);
  tester.wrap_free(small1);
  tiny1 = (char *)tester.wrap_malloc(sizeof(char) * 80, (uintptr_t)tiny1);
  tiny2 = (char *)tester.wrap_malloc(sizeof(char) * 105, (uintptr_t)tiny2);
  tiny3 = (t_nest *)tester.wrap_malloc(sizeof(t_nest), (uintptr_t)tiny3);
  tiny4 = (t_test *)tester.wrap_malloc(sizeof(t_test), (uintptr_t)tiny4);
  small1 = (char *)tester.wrap_malloc(sizeof(char) * 651, (uintptr_t)small1);
  small2 = (char *)tester.wrap_malloc(sizeof(char) * 512, (uintptr_t)small2);
  small3 = (char *)tester.wrap_malloc(sizeof(char) * 817, (uintptr_t)small3);
  small4 = (char *)tester.wrap_malloc(sizeof(char) * 353, (uintptr_t)small4);
  tester.wrap_free(tiny2);
  tester.wrap_free(tiny3);
  tester.wrap_free(small3);
  tester.wrap_free(small1);
  tiny1 = (char *)tester.wrap_malloc(sizeof(char) * 80, (uintptr_t)tiny1);
  tiny2 = (char *)tester.wrap_malloc(sizeof(char) * 105, (uintptr_t)tiny2);

  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  // tiny1 = ft_malloc(sizeof(char) * 80);
  // tiny2 = ft_malloc(sizeof(char) * 105);
  // tiny3 = ft_malloc(sizeof(t_nest));
  // tiny4 = ft_malloc(sizeof(t_test));
  // small1 = ft_malloc(sizeof(char) * 651);
  // small2 = ft_malloc(sizeof(char) * 512);
  // small3 = ft_malloc(sizeof(char) * 817);
  // small4 = ft_malloc(sizeof(char) * 353);
  // tester.wrap_free(tiny2);
  // tester.wrap_free(tiny3);
  // tester.wrap_free(small3);
  // tester.wrap_free(small1);
  //
  show_alloc_mem();
  return 0;
}
// int main() {
//   char *tiny1 = ft_malloc(sizeof(char) * 82);
//   char *tiny2 = ft_malloc(sizeof(char) * 107);
//   t_nest *tiny3 = ft_malloc(sizeof(t_nest));
//   t_test *tiny4 = ft_malloc(sizeof(t_test));
//   char *small1 = ft_malloc(sizeof(char) * 651);
//   char *small2 = ft_malloc(sizeof(char) * 512);
//   char *small3 = ft_malloc(sizeof(char) * 817);
//   char *small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//   tiny1 = ft_malloc(sizeof(char) * 80);
//   tiny2 = ft_malloc(sizeof(char) * 105);
//   tiny3 = ft_malloc(sizeof(t_nest));
//   tiny4 = ft_malloc(sizeof(t_test));
//   small1 = ft_malloc(sizeof(char) * 651);
//   small2 = ft_malloc(sizeof(char) * 512);
//   small3 = ft_malloc(sizeof(char) * 817);
//   small4 = ft_malloc(sizeof(char) * 353);
//   tester.wrap_free(tiny2);
//   tester.wrap_free(tiny3);
//   tester.wrap_free(small3);
//   tester.wrap_free(small1);
//
//   show_alloc_mem();
//   return 0;
// }
